---
# This playbook showcase simple ping rhel server command.

- name: Ping instances
  hosts: rhel-aws-hosts
  connection: ssh
  remote_user: ec2-user
  gather_facts: False

  tasks:
  - name: ping aws rhel hosts
    ping:
