---
# This playbook showcases checking our server envrionment is ready for JBoss EAP install.

- name: Discover Java Facts on Remote Windows
  hosts: win-aws-hosts2
  
  tasks:
    - name: Gather Java Facts
      win_stat:
        path: C:\Program Files\Java\jdk1.8.0_121
      register: file_info

    - debug: 
        var: file_info